<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * cashbackTrackingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cashbackTrackingsRepository extends \Doctrine\ORM\EntityRepository
{
}
