<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * cashbackTransactionsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cashbackTransactionsRepository extends \Doctrine\ORM\EntityRepository
{
    public function setDoubleCachBack(&$em, $id)
    {
        $cashbackTransactions = $em->getRepository('iFlairLetsBonusAdminBundle:cashbackTransactions')->findOneBy(array('id' => $id));
        $cashbackTransactions->setAmount($cashbackTransactions->getAmount() * 2);
        $em->persist($cashbackTransactions);
        $em->flush();
    }
}
