<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class childCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
