<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsAllhelpRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsAllhelpRepository extends \Doctrine\ORM\EntityRepository
{
}
