<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsCookiespolicyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsCookiespolicyRepository extends \Doctrine\ORM\EntityRepository
{
}
