<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsCreateclaimRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsCreateclaimRepository extends \Doctrine\ORM\EntityRepository
{
}
