<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsHowitworksRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsHowitworksRepository extends \Doctrine\ORM\EntityRepository
{
}
