<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsLegalWarningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsLegalWarningRepository extends \Doctrine\ORM\EntityRepository
{
}
