<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsSitemapRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsSitemapRepository extends \Doctrine\ORM\EntityRepository
{
}
