<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * CmsTermsandconditionsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsTermsandconditionsRepository extends \Doctrine\ORM\EntityRepository
{
}
