<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * DomainRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainRepository extends \Doctrine\ORM\EntityRepository
{
}
