<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * MailchimpListsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailchimpListsRepository extends \Doctrine\ORM\EntityRepository
{
}
