<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * NewslettertemplateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewslettertemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
