<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * offerSpecialsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offerSpecialsRepository extends \Doctrine\ORM\EntityRepository
{
}
