<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Shoppiday\CommonBundle\Traits\Repository;

/**
 * ShopRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    use Repository;

    /**
     * Method that return the number of rows actives on an entity
     * @return int
     */
    public function countActive()
    {
        try {
            $entity = $this->getEntityName();

            return $this->_em->createQuery('SELECT COUNT(a.id) FROM '.$entity.' a 
            WHERE a.startDate<=:now AND a.endDate>=:now AND a.shopStatus = 1')
                ->setParameter('now', date('Y-m-d'))
                ->setCacheable(true)
                ->setQueryCacheLifetime(600)
                ->getSingleScalarResult();
        } catch (\Exception $e) {
            return -1;
        }
    }
}
