<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * VariationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariationRepository extends \Doctrine\ORM\EntityRepository
{
    public function addRowVariation(&$em, $shopObject, $shopHistoryObject)
    {
        foreach ($shopObject->getShopVariation() as $shopVariation) {
            $variation = new Variation();
            //$variation->setId($shopVariation->getId());
            $variation->setShopVariationId($shopVariation->getId());
            $variation->setNumber($shopVariation->getNumber());
            $variation->setTitle($shopVariation->getTitle());
            $variation->setDate($shopVariation->getDate());
            $variation->setShopHistory($shopHistoryObject);
            $em->persist($variation);
            $em->flush();
        }
    }

    public function updateRowVariation(&$em, $shopObject, $shopHistoryObject)
    {
        if ($this->deleteRowVariation($em, $shopObject, $shopHistoryObject)) {
            $this->addRowVariation($em, $shopObject, $shopHistoryObject);
        }
    }

    public function deleteRowVariation(&$em, $shopObject, $shopHistoryObject)
    {
        $variations = $em->getRepository('iFlairLetsBonusAdminBundle:Variation')->findByShopHistory(array($shopHistoryObject->getId()));

        if ($variations) {
            foreach ($variations as $variation) {
                $em->remove($variation);
                $em->flush();
            }
        }

        return true;
    }
}
