<?php

namespace iFlair\LetsBonusAdminBundle\Entity;

/**
 * VoucherTradeDoublerSiteTokenRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoucherTradeDoublerSiteTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
