<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ApprovedContributionFestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovedContributionFestivalRepository extends \Doctrine\ORM\EntityRepository
{
}
