<?php

namespace IFlairFestivalBundle\Repository;

/**
 * artistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class artistRepository extends \Doctrine\ORM\EntityRepository
{
}
