<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ContributionAddImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionAddImageRepository extends \Doctrine\ORM\EntityRepository
{
}
