<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ContributionAddFestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionAddFestivalRepository extends \Doctrine\ORM\EntityRepository
{
}
