<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ContributionAddMusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionAddMusicRepository extends \Doctrine\ORM\EntityRepository
{
}
