<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ContributionAddFeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionAddFeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
