<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ContributionAdddFestivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionAdddFestivalRepository extends \Doctrine\ORM\EntityRepository
{
}
