<?php

namespace IFlairFestivalBundle\Repository;

/**
 * ContributionAddRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionAddRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
