<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_artistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_artistRepository extends \Doctrine\ORM\EntityRepository
{
}
