<?php

namespace IFlairFestivalBundle\Repository;

/**
 * Festival_PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Festival_PaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
