<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
