<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressRatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressRatingsRepository extends \Doctrine\ORM\EntityRepository
{
}
