<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressFeaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressFeaturesRepository extends \Doctrine\ORM\EntityRepository
{
}
