<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_rating_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_rating_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
