<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festivalFavouriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festivalFavouriteRepository extends \Doctrine\ORM\EntityRepository
{
}
