<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInfoEditConfirmationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInfoEditConfirmationRepository extends \Doctrine\ORM\EntityRepository
{
}
