<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressPaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressPaymentsRepository extends \Doctrine\ORM\EntityRepository
{
}
