<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_type_ratingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_type_ratingsRepository extends \Doctrine\ORM\EntityRepository
{
}
