<?php

namespace IFlairFestivalBundle\Repository;

/**
 * Festival_inprogress_statusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Festival_inprogress_statusRepository extends \Doctrine\ORM\EntityRepository
{
}
