<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressMultipleImageUploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressMultipleImageUploadRepository extends \Doctrine\ORM\EntityRepository
{
}
