<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressDatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressDatesRepository extends \Doctrine\ORM\EntityRepository
{
}
