<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_searchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_searchRepository extends \Doctrine\ORM\EntityRepository
{
}
