<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_locationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_locationRepository extends \Doctrine\ORM\EntityRepository
{
}
