<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalUploadedImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalUploadedImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
