<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_attendeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_attendeesRepository extends \Doctrine\ORM\EntityRepository
{
}
