<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festivalVisitedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festivalVisitedRepository extends \Doctrine\ORM\EntityRepository
{
}
