<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_featuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_featuresRepository extends \Doctrine\ORM\EntityRepository
{
}
