<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festival_viewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festival_viewRepository extends \Doctrine\ORM\EntityRepository
{
}
