<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressRepository extends \Doctrine\ORM\EntityRepository
{
}
