<?php

namespace IFlairFestivalBundle\Repository;

/**
 * festivalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class festivalRepository extends \Doctrine\ORM\EntityRepository
{
}
