<?php

namespace IFlairFestivalBundle\Repository;

/**
 * FestivalInprogressMusicgenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivalInprogressMusicgenreRepository extends \Doctrine\ORM\EntityRepository
{
}
