<?php

namespace iFlair\LetsBonusFrontBundle\Entity;

/**
 * NewsletterSubscriptionUsersRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterSubscriptionUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
