<?php

namespace Galop\AdminBundle\Repository;

/**
 * AdvertisementZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
