<?php

namespace Galop\AdminBundle\Repository;

/**
 * ApiArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
