<?php

namespace Galop\AdminBundle\Repository;

/**
 * NewsDesciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsDesciplineRepository extends \Doctrine\ORM\EntityRepository
{
}
