<?php

namespace Galop\AdminBundle\Repository;

/**
 * NewsRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
