<?php

namespace Galop\AdminBundle\Repository;
use Liplex\MultipleFileUploadBundle\Repository\MultipleFileUploadRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends MultipleFileUploadRepository
{
	public function getMediaPreviewOnEdit($media, $container, $size)
    {
        $mediaManager = $container->get('sonata.media.pool');
        $provider = $mediaManager->getProvider($media->getProviderName());
        $mediaPreviewUrl = $provider->generatePublicUrl($media, $size);
        if ($mediaPreviewUrl) {
            $imageMediaPreview = '<img src="'.$mediaPreviewUrl.'" class="admin-preview" />';
        } else {
            $imageMediaPreview = '';
        }

        return $imageMediaPreview;
    }
}
