<?php

namespace Galop\AdminBundle\Repository;

/**
 * SubscriptionPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
