<?php

namespace Galop\AdminBundle\Repository;

/**
 * SystemEditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemEditorRepository extends \Doctrine\ORM\EntityRepository
{
}
