fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_google_login:
    path: /login/check-google

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    # schemes:  [https]

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_user_admin_security_logout:
    path: /logout

sac_front_user:
    path:     /admin/sac
    defaults: { _controller: iFlairLetsBonusAdminBundle:Sac:index }

sac_front_user_view:
    path:     /admin/sac/users/view/{id}
    defaults: { _controller: iFlairLetsBonusAdminBundle:Sac:view }

sac_transaction_report:
    path:     /admin/sac/Reports/transactionswithoutuser
    defaults: { _controller: iFlairLetsBonusAdminBundle:Sac:report }

sac_front_user_ajaxfilter:
    path:     /admin/sac/users/ajaxfilter/{id}
    defaults: { _controller: iFlairLetsBonusAdminBundle:Sac:filter }

sac_front_user_userajaxfilter:
    path:     /admin/sac/users/userajaxfilter
    defaults: { _controller: iFlairLetsBonusAdminBundle:Sac:userfilter }

sac_front_user_report_export_shops:
    path:     /admin/Reports/exportShops
    defaults: { _controller: iFlairLetsBonusAdminBundle:ExportShopAdmin:index }

sac_front_user_report_without_sales:
    path:     /admin/Reports/transactionswithoutuser
    defaults: { _controller: iFlairLetsBonusAdminBundle:ExportShopAdmin:userreport }

search_logs:
    path:     /admin/Searchlogs
    defaults: { _controller: iFlairLetsBonusAdminBundle:Searchlogs:index }

search_logs_userajaxfilter:
    path:     /admin/Searchlogs/userajaxfilter
    defaults: { _controller: iFlairLetsBonusAdminBundle:Searchlogs:userfilter }

i_flair_lets_bonus_financial:
    path: admin/financiallisting/makepayment

i_flair_lets_bonus_mtfview:
    path:  mtfview
    defaults: { _controller: iFlairLetsBonusAdminBundle:FinancialAdmin:mtfview }
    options:  { mobile: redirect, tablet: no_redirect, full: redirect_without_path }

i_flair_lets_bonus_financial_list:
    path: /admin/financial/list

i_flair_lets_bonus_financial_newlist:
    path: /admin/financial/newlist
    defaults: { _controller: iFlairLetsBonusAdminBundle:FinancialAdmin:newlist }

shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'